name: 'that girl, Melody'
favicon: null
layout_spectrum: 0.1419770542997867
typography_spectrum: 0.39152398938313127
title: 'That girl, Melody'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10199227533303201
  lightness: 0.7677972216624767
  saturation: 0.8870479047764093
  rhythmicContrast: 0.0810931553132832
purpose: []
