name: 'That girl, Melody'
favicon: null
layout_spectrum: 0.01968
typography_spectrum: 0.29309
title: 'That girl, Melody'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#30214b'
    - '#d7d0a9'
    - '#9996ab'
    - '#a3639a'
    - '#33797a'
  brandStrength: 0.4375
  lightness: 0.7677972216624767
  saturation: 0.8870479047764093
  rhythmicContrast: 0.0810931553132832
purpose: []
